version: "3.9"

services:
  app:
    build: .
    container_name: ratmir_app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: ratmer
    volumes:
      - ./uploads:/app/uploads
      - ./obxod:/app/obxod

  db:
    image: mysql:8.0
    container_name: ratmir_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratmer
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ratmir_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
